version: '3.1'
services:
  agent:
    image: ado-agents/ado-agent-linux:latest
    build: 
      context: .
      args:
        - ARCH=amd64
        - AGENT_VERSION=3.220.5
    env_file:
      - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - logs:/var/log
    restart: always
volumes:
  logs: {}
