version: '3.1'
services:
  agent:
    image: ado-agents/ado-agent-win-amd64:latest
    build: 
      context: .
      args:
        - AGENT_VERSION=3.240.1
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
    # volumes:
    restart: always
volumes:
  logs: {}
