name: Github Actions Runner Deploy
description: Deploys ACI from github actions runner image published to ACR

inputs:
  AZURE_CREDENTIALS:
    description: 'AZURE_CREDENTIALS'
    required: true
  AZURE_RG:
    required: true
    description: AZURE_RG
  ROOT:
    required: true
    description: ROOT
  ACR_NAME:
    required: true
    description: ACR_NAME
  ACI_NAME:
    required: true
    description: ACI_NAME
  GITHUB_TOKEN:
    required: true
    description: GITHUB_TOKEN
  GITHUB_REPOSITORY:
    required: true
    description: GITHUB_REPOSITORY
  IMAGE_NAME:
    required: true
    description: IMAGE_NAME
  ACR_SERVER:
    required: true
    description: ACR_SERVER
  INSTANCES_COUNT:
    description: Number of container instances
    default: '2'
  SUBNET_ID:
    description: Virtual network subnet resource Id.
    default: ''
  DNS_SERVERS:
    description: Private DNS Servers to use for container instances.
    default: '[]' 
  OS:
    description: OS type of the container instance.
    default: 'Linux'

runs:
  using: "composite"
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Deploy ACI
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
            # get the ACR password
            user=${{ inputs.ACR_NAME }}
            password=$(az acr credential show -n $user --query "passwords[0].value" -o tsv)

            environmentVariables='[
              {"name":"GITHUB_TOKEN","secureValue":"${{ inputs.GITHUB_TOKEN }}"},
              {"name":"GITHUB_REPOSITORY","value":"${{ inputs.GITHUB_REPOSITORY }}"}
            ]'

            [ -n '${{ inputs.DNS_SERVERS }}' ] && dnsServers='${{ inputs.DNS_SERVERS }}' || dnsServers='[]'

            # deploy ACI
            az deployment group create \
              --name "deploy-${{ inputs.ACI_NAME }}" \
              --resource-group ${{ inputs.AZURE_RG }} \
              --template-file ${{ inputs.ROOT }}/main.bicep \
              --parameters ${{ inputs.ROOT }}/main.parameters.json \
              --parameters name=${{ inputs.ACI_NAME }} \
                          image=${{ inputs.IMAGE_NAME }} \
                          osType=${{ inputs.OS }} \
                          imageServer=${{ inputs.ACR_SERVER }} \
                          imageServerUsername="$user" \
                          imageServerPassword="$password" \
                          instances=${{ inputs.INSTANCES_COUNT }} \
                          environmentVariables="$environmentVariables" \
                          dnsServers="$dnsServers" \
                          subnetResourceId=${{ inputs.SUBNET_ID }}
              

    