version: '3.1'
services:
  runner:
    image: github-runners/github-runner-linux:latest
    build: .
    env_file:
      - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - logs:/var/log
    restart: always
volumes:
  logs: {}
