version: '3.1'
services:
  agent:
    image: ado-agents/ado-agent-linux-arm64:latest
    build: 
      context: .
      args:
        - ARCH=arm64
        - AGENT_VERSION=3.240.1
    env_file:
      - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - logs:/var/log
    restart: always
volumes:
  logs: {}
