name: Github Actions Runner Build
description: Builds github actions runner container image and push to ACR

inputs:
  AZURE_CREDENTIALS:
    description: 'AZURE_CREDENTIALS'
    required: true
  ACR_NAME:
    description: 'ACR_NAME'
    required: true
  RUNNER_ROOT:
    description: 'RUNNER_ROOT'
    required: true
  IMAGE_NAME:
    required: true
    description: IMAGE_NAME    
  IMAGE_VERSION:
    description: 'IMAGE_VERSION'
    required: true
  ACR_SERVER:
    description: ACR_SERVER
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Get registry credentials
      id: acr_credentials
      uses: ./.github/actions/acr-credentials
      with:
        ACR_NAME: ${{ inputs.ACR_NAME }}
    
    - name: 'Docker login'
      shell: pwsh
      run: docker login ${{ inputs.ACR_SERVER }} -u ${{ steps.acr_credentials.outputs.ACR_USERNAME }} -p ${{ steps.acr_credentials.outputs.ACR_PASSWORD }}

    - name: 'Build & Push image'
      shell: pwsh
      run: |
          cd ${{ inputs.RUNNER_ROOT }}
          docker-compose up --build --detach
          docker tag ${{ inputs.IMAGE_NAME }}:latest ${{ inputs.ACR_SERVER }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_VERSION }}
          docker tag ${{ inputs.IMAGE_NAME }}:latest ${{ inputs.ACR_SERVER }}/${{ inputs.IMAGE_NAME }}:latest
          docker image push --all-tags ${{ inputs.ACR_SERVER }}/${{ inputs.IMAGE_NAME }}
