version: '3.1'
services:
  agent:
    image: github-runners/github-runner-win-amd64:latest
    build: 
      context: .
      args:
        - RUNNER_VERSION=2.317.0
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
    # volumes:
    restart: always
volumes:
  logs: {}
