version: '3.1'
services:
  runner:
    image: github-runners/github-runner-linux-amd64:latest
    build: 
      context: .
      args:
        - ARCH=amd64
        - RUNNER_VERSION=2.317.0
    env_file:
      - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - logs:/var/log
    restart: always
volumes:
  logs: {}
