version: '3.1'
services:
  agent:
    image: ado-agents/ado-agent-win:latest
    build: 
      context: .
      args:
        - ARCH=amd64
        - AGENT_VERSION=3.220.5
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
    # volumes:
    restart: always
volumes:
  logs: {}
