name: ACR credentials
description: Get Azure Container Registry credentials

inputs:
  ACR_NAME:
    description: 'ACR_NAME'
    required: true

outputs:
  ACR_USERNAME:
    description: 'ACR_USERNAME'
    value: ${{ steps.acr.outputs.ACR_USERNAME }}
  ACR_PASSWORD:
    description: 'ACR_PASSWORD'
    value: ${{ steps.acr.outputs.ACR_PASSWORD }}

runs:
  using: "composite"
  steps:
    - name: Get registry credentials
      id: acr
      shell: pwsh
      run: |
          $ACR_USERNAME = (az acr credential show -n "${{ inputs.ACR_NAME }}" --query "username" -o tsv)
          "ACR_USERNAME=$ACR_USERNAME" | Out-File "$env:GITHUB_OUTPUT" -Encoding utf8 -Append
    
          $ACR_PASSWORD = (az acr credential show -n "${{ inputs.ACR_NAME }}" --query "passwords[0].value" -o tsv)
          Write-Host "::add-mask::$ACR_PASSWORD"
          "ACR_PASSWORD=$ACR_PASSWORD" | Out-File "$env:GITHUB_OUTPUT" -Encoding utf8 -Append
